id: 6g245mu7
name: docmanage
app:
  host: 0.0.0.0
  port: 8002
  debug: false
deploy:
  host: 139.196.37.224
  port: 8002
databases:
  mongo:
    dialect: mongodb
    host: 127.0.0.1
    port: 27017
    username: root
    password: ""
    database: test
  mysql:
    dialect: mysql
    host: 127.0.0.1
    port: 3306
    username: root
    password: ""
    database: docloud
celery:
  worker: 4
switch:
  cron:
    report_daily: False
