id: 6g245mu7
name: docmanage
app:
  host: 0.0.0.0
  port: 3000
  debug: false
databases:
  mongo:
    alias: mongodb
    host: 127.0.0.1
    port: 27017
    username: root
    password: ""
    database: test
  mysql:
    alias: mysql
    host: 127.0.0.1
    port: 3306
    username: root
    password: "+"
    database: docloud
celery:
  worker: 4
switch:
  cron:
    report_daily: False